apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stable-diffusion-webui
  namespace: perian
spec:
  destination:
    namespace: perian-stable-diffusion-webui
    server: https://kubernetes.default.svc
  project: perian
  source:
    repoURL: https://ppts-ai.github.io/apps/
    chart: stable-diffusion-webui
    targetRevision: 0.1.0
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stable-diffusion-webui-ingress
  namespace: quendi-stable-diffusion-webui
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "5"
    nginx.ingress.kubernetes.io/limit-rpm: "100"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    traefik.ingress.kubernetes.io/router.tls: "false"
    kubernetes.io/ingress.class: "traefik"
spec:
  ingressClassName: traefik
  rules:
    - host: stable-diffusion-webui.kidd.network
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stable-diffusion-webui
                port:
                  number: 80