apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stable-diffusion-webui
  namespace: perian
spec:
  destination:
    namespace: perian-stable-diffusion-webui
    server: https://kubernetes.default.svc
  project: perian
  source:
    repoURL: https://ppts-ai.github.io/apps/
    chart: stable-diffusion-webui
    targetRevision: 0.1.0
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true