# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: unifi
#   namespace: perian
# spec:
#   project: perian
#   source:
#     repoURL: https://github.com/andrewiankidd/pi-k3s-gitops
#     targetRevision: feature/master-node
#     path: src/kubernetes/perian/unifi
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: perian-unifi
#   syncPolicy:
#     syncOptions:
#       - CreateNamespace=true
#     automated:
#       prune: true
#       selfHeal: true