apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: quendi
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: quendi
  source:
    chart: headlamp
    repoURL: https://headlamp-k8s.github.io/headlamp/
    targetRevision: 0.27.0
    helm:
      releaseName: headlamp
  destination:
    server: https://kubernetes.default.svc
    namespace: quendi-headlamp
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: headlamp-ingress
  namespace: quendi-headlamp
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "5"
    nginx.ingress.kubernetes.io/limit-rpm: "100"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    traefik.ingress.kubernetes.io/router.tls: "true"
    kubernetes.io/ingress.class: "traefik"
spec:
  ingressClassName: traefik
  rules:
    - host: headlamp.kidd.network
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: headlamp
                port:
                  number: 80