apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lgtm
  namespace: quendi
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: quendi
  sources:
    - repoURL: https://grafana.github.io/helm-charts/
      targetRevision: 2.1.0
      chart: lgtm-distributed
    - repoURL: https://github.com/andrewiankidd/pi-k3s-gitops.git
      targetRevision: feature/master-node
      path: src/kubernetes/quendi/lgtm
  destination:
    server: https://kubernetes.default.svc
    namespace: quendi-lgtm
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true