apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitwarden
  namespace: atani
spec:
  destination:
    namespace: atani-nginx
    server: https://kubernetes.default.svc
  project: atani
  source:
    repoURL: https://charts.bitwarden.com/
    chart: bitwarden/self-host
    helm:
      valuesObject:
        domain: bitwarden.kidd.network
        ingress:
          enabled: false
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bitwarden-ingress
  namespace: atani-bitwarden
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "5"
    nginx.ingress.kubernetes.io/limit-rpm: "100"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    traefik.ingress.kubernetes.io/router.tls: "false"
    kubernetes.io/ingress.class: "traefik"
spec:
  ingressClassName: traefik
  rules:
    - host: bitwarden.kidd.network
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bitwarden
                port:
                  number: 80
