apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitwarden
  namespace: atani
spec:
  destination:
    namespace: atani-nginx
    server: https://kubernetes.default.svc
  project: atani
  sources:
    - repoURL: https://charts.bitwarden.com/
      chart: self-host
      targetRevision: '*'
    - repoURL: https://github.com/andrewiankidd/pi-k3s-gitops.git
      targetRevision: feature/master-node
      path: src/kubernetes/atani/bitwarden
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true