apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: atani
spec:
  destination:
    namespace: atani-nginx
    server: https://kubernetes.default.svc
  project: atani
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: nginx
      targetRevision: 18.3.5
    - repoURL: https://github.com/andrewiankidd/pi-k3s-gitops.git
      targetRevision: feature/master-node
      path: src/kubernetes/atani/nginx
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true