apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi
  namespace: perian-unifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifi
  template:
    metadata:
      labels:
        app: unifi
    spec:
      containers:
        - name: unifi
          image: linuxserver/unifi-controller
          ports:
            - containerPort: 8443